-- ============================================
-- Soporte para múltiples compañeros de coche (carpooling)
-- ============================================

-- Nueva tabla para relacionar reservas con varios compañeros
create table if not exists public.booking_carpool_users (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz default now()
);

-- Índices para búsquedas rápidas
create index if not exists idx_booking_carpool_users_booking_id
  on public.booking_carpool_users(booking_id);

create index if not exists idx_booking_carpool_users_user_id
  on public.booking_carpool_users(user_id);

-- Migrar datos existentes desde bookings.carpool_with_user_id (si se usaba el modelo antiguo)
insert into public.booking_carpool_users (booking_id, user_id)
select b.id, b.carpool_with_user_id
from public.bookings b
where b.carpool_with_user_id is not null
  and not exists (
    select 1
    from public.booking_carpool_users bcu
    where bcu.booking_id = b.id
      and bcu.user_id = b.carpool_with_user_id
  );

-- Nota:
-- - La columna public.bookings.carpool_with_user_id se puede mantener por compatibilidad
--   o eliminar en una migración posterior si ya no se usa.

